### ISSUE TITLE
What does this comment mean please?

### ISSUE THREAD

**Issue by bdeanindy** [grokify/ringcentral-oauth-demos#4]
On this line: https://github.com/grokify/ringcentral-demos-oauth/blob/master/javascript-express/app.js#L50

What does the comment "optional if 1 configured" mean please?

I thought for 3-legged OAuth the `redirectURI` was a mandatory component?

**Comment by grokify** [comment]
For the Authorization Code flow to work, one or more redirect URIs must be configured for the app within the Developer Portal, however if only 1 URI is configured, it does not need to be sent in the OAuth authorization token request. Basically:
- If only 1 redirect URI is configured for the app in the Developer Portal, the OAuth authorization code request does not need to include the redirect URI because the redirect URI is implicitly known given there is only 1. The single redirect URI will be used.
- If more than 1 redirect URI is configured for the app in the Developer Portal, one of the matching redirect URIs must be included in the authorization code request because the system would otherwise not know which URI to redirect the browser to.
